apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    testing.upbound.io/example-name: sg-us-east-1
  name: sg-us-east-1
spec:
  deletionPolicy: Delete
  forProvider:
    description: sample-app-security-group                
    groupName: sample-app-security-group                 
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc-us-east-1