apiVersion: ecs.aws.crossplane.io/v1alpha1
kind: TaskDefinition
metadata:
  labels:
    testing.upbound.io/example-name: sample-app-task
  name: sample-app-task
spec:
  forProvider:
    family: example-task-definition-nginx
    cpu: "2048"
    memory: "4096"
    networkMode: awsvpc
    requiresCompatibilities:
      - FARGATE
    executionRoleARNSelector:
      matchLabels:
        testing.upbound.io/example-name: ecs-role
    taskRoleARNSelector:
      matchLabels:
        testing.upbound.io/example-name: ecs-role
    region: us-east-1
    containerDefinitions:
      - name: sample-app-container
        image: nginxdemos/hello
        cpu: 256
        memoryReservation: 512
        essential: true
        portMappings:
          - containerPort: 80
            hostPort: 80
            protocol: tcp