apiVersion: ecs.aws.crossplane.io/v1alpha1
kind: Service
metadata:
  labels:
    testing.upbound.io/example-name: sample-app-service
  name: sample-app-service
spec:
  forProvider:
    desiredCount: 1
    deploymentController:
      type_: ECS
    deploymentConfiguration:
      maximumPercent: 200
      minimumHealthyPercent: 0
    launchType: FARGATE
    region: us-east-1
    schedulingStrategy: REPLICA
    platformVersion: 1.4.0 
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-app-cluster
    loadBalancers:
    - containerName: sample-app-container
      containerPort: 80
      targetGroupARNSelector:
        matchLabels:
          testing.upbound.io/example-name: sample-app-target-group
    networkConfiguration:
      awsvpcConfiguration:
        assignPublicIP: ENABLED
        securityGroupSelector:
          matchLabels:
            testing.upbound.io/example-name: sg-us-east-1
        subnetSelector:
          matchLabels:
            all-subnets: included
    taskDefinitionSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-app-task
